# Generated by Django 3.0.8 on 2020-08-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumakerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentialsmodel',
            old_name='credential',
            new_name='credentials',
        ),
    ]
